# Generated by Django 2.0.3 on 2019-05-04 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='create_time',
            new_name='create_date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='published_time',
            new_name='published_date',
        ),
    ]
